project_id = "velpueasbsrptocrjljg"

[functions.generate-weelmat]
verify_jwt = true

[functions.generate-weelmat-premium]
verify_jwt = true

[functions.generate-lesson-plan]
verify_jwt = true

[functions.generate-periodical-test]
verify_jwt = true

[functions.extract-weelmat-data]
verify_jwt = true

[functions.submit-weelmat]
verify_jwt = true

[functions.generate-logsheet]
verify_jwt = true

[functions.get-school-status]
verify_jwt = false
