// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwpjdpdquywuyhbrgzku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3cGpkcGRxdXl3dXloYnJnemt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM4MTg1MTksImV4cCI6MjA5OTM5NDUxOX0.mD2ewPmmNOwDPHbluiBVNbGeoLaIbwo9-N8hZxrXTsk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});