// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://velpueasbsrptocrjljg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZlbHB1ZWFzYnNycHRvY3JqbGpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMzA5MTEsImV4cCI6MjA2ODcwNjkxMX0.nglCOP6Ol7c0tZCCs-tG6E5NDhKwoTwsgriZfPD2W7c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});